---
- name: install and configure tomcat 9
  hosts: appserver
  become: yes
  vars:
    - java_package: openjdk-11-jdk
    - tomcat_username: tomcat
    - tomcat_home: /opt/tomcat
    - tomcat_shell: /bin/false
    - tomcat_version: "9.0.54"
  tasks:
    - name: upadate packages and install tomcat 9
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: add a tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_username }}"
        home: "{{ tomcat_home }}"
        shell: "{{ tomcat_shell }}"
        state: present
    - name: download the tomcat distribution
    get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{tomcat_version }}.tar.gz"
        dest: "/tem/apache-tomcat-{{tomcat_version}}.tar.gz"
    - name: untar the tomcat distribution
      ansible.builtin.unarchive:
        src: "/tem/apache-tomcat-{{tomcat_version}}.tar.gz"
        dest: "{{ tomcat_home }}"
        